[project]
name = "label-studio"
version = "1.23.0.dev0"
description = "Label Studio annotation tool"
authors = [
    { name = "HumanSignal", email = "support@humansignal.com" },
]
readme = "README.md"
license = "Apache-2.0"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.13,<4"
dependencies = [
    "appdirs (>=1.4.3)",
    "pyyaml (>=6.0.0)",
    "azure-storage-blob (>=12.6.0)",
    "boto3 (>=1.28.58,<2.0.0)",
    "botocore (>=1.39.3,<2.0.0)",
    "bleach (>=6.3.0)",
    "Django (>=6.0.0)",
    "django-storages (>=1.14.6)",
    "django-annoying (>=0.10.8)",
    "django-debug-toolbar (>=6.1.0)",
    "django-environ (>=0.12.0)",
    "django-filter (>=25.2)",
    "django-model-utils (>=5.0.0)",
    "django-rq (>=3.2.1)",
    "django-cors-headers (>=4.9.0)",
    "django-extensions (>=4.1)",
    "django-user-agents (>=0.4.0)",
    "django-ranged-fileresponse (>=0.1.2)",
    "drf-dynamic-fields (>=0.4.0)",
    "djangorestframework (>=3.16.1)",
    "drf-flex-fields (>=1.0.2)",
    "drf-spectacular (>=0.29.0)",
    "drf-generators (>=0.5.0)",
    "lxml[html-clean] (>=6.0.2)",
    "defusedxml (>=0.7.1)",
    "numpy (>=2.2.6,<3.0.0)",
    "pandas (>=2.3.3)",
    "psycopg[binary] (>=3.2.0,<4.0.0)",
    "pydantic (>=2.9.2)",
    "pytz (>=2025.2)",
    "requests (>=2.32.3)",
    "rq (>=2.6)",
    "rules (>=3.5)",
    "ujson (>=5.11.0)",
    "ijson (>=3.4.0)",
    "xmljson (>=0.2.1)",
    "colorama (>=0.4.4)",
    "pyboxen (>=1.3.0)",
    "redis (>=7.1.0)",
    "sentry-sdk (>=2.48.0)",
    "launchdarkly-server-sdk (>=8.2.1)",
    "python-json-logger (>=4.0.0)",
    "google-cloud-storage (>=2.13.0)",
    "google-cloud-logging (>=3.10.0)",
    "django-csp (>=4.0)",
    "django-migration-linter (>=5.2.0)",
    "djangorestframework-simplejwt[crypto] (>=5.4.0)",
    "tldextract (>=5.1.3)",
    "uuid-utils (>=0.11.0,<1.0.0)",
    ## HumanSignal repo dependencies :start
    "label-studio-sdk @ https://github.com/HumanSignal/label-studio-sdk/archive/93d3b85e1162f2cb2dc5efb25c8d0a0b0f759e7c.zip",
    ## HumanSignal repo dependencies :end
    "grpcio-reflection (>=1.76.0,<2.0.0)",
    "nbformat (>=5.10.4,<6.0.0)",
    "zmq (>=0.0.0,<0.0.1)",
    "pytest-asyncio (>=1.3.0,<2.0.0)",
    "deptry (>=0.24.0,<0.25.0)",
]

[project.urls]
Repository = "https://github.com/HumanSignal/label-studio"

[project.scripts]
label-studio = "label_studio.server:main"

[project.optional-dependencies]
uwsgi = ['pyuwsgi (>=2.0.30)', 'uwsgitop (>=0.12)']

[tool.ruff]
# Assume Python 3.13 at a minimum
target-version = "py313"

# Same as Blue.
line-length = 119

[tool.ruff.lint]
# Enable the pycodestyle (`E`) and Pyflakes (`F`) rules by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    # isort
    "I001"
]
ignore = [
    "E501",
    "E402", # ignores: Module level import not at top of file.  (isort takes care of this and if not, there is usually a good reason)
]



# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "**/migrations/*.py",
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
# Ignore deleting imports in __init__.py files as they're actually being used.
"__init__.py" = ["F401"]
"**/settings/label_studio.py" = ["F405"]
"test*.py" = ["F811"]


[tool.blue]

line-length = 119

include = 'label_studio/.*\.py$'

# Exclude a variety of commonly ignored directories, as well as all migrations files.
force-exclude = '''
/(
    \.bzr
  | \.direnv
  | \.eggs
  | \.git
  | \.github
  | \.git-rewrite
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.pants.d
  | \.pytype
  | \.ruff_cache
  | \.svn
  | \.tox
  | \.venv
  | \.hg
  | _build
  | buck-out
  | build
  | dist
  | node_modules
  | migrations
  | venv
  | __pycache__
)/
'''

target-version = ['py313']

[tool.poetry]

packages = [
    { include = "label_studio" },
]
include = [
    { path = "web/dist/libs/datamanager/**/*", format = ["sdist", "wheel"] },
    { path = "web/dist/libs/editor/**/*", format = ["sdist", "wheel"] },
    { path = "web/dist/apps/labelstudio/**/*", format = ["sdist", "wheel"] },
    { path = "label_studio/annotation_templates/**/*", format = ["sdist", "wheel"] },
    { path = "label_studio/core/static/**/*", format = ["sdist", "wheel"] },
    { path = "label_studio/core/static_build/**/*", format = ["sdist", "wheel"] },
    { path = "label_studio/core/utils/schema/*.json", format = ["sdist", "wheel"] },
    { path = "label_studio/core/templatetags/*.py", format = ["sdist", "wheel"] },
    { path = "label_studio/core/version_.py", format = ["sdist", "wheel"] },
    { path = "label_studio/core/all_urls.json", format = ["sdist", "wheel"] },
    { path = "label_studio/io_storages/**/*.yml", format = ["sdist", "wheel"] },
]

exclude = [
    { path = "label_studio/frontend", format = ["sdist", "wheel"] },
]

requires-poetry = '>=2.0.0,<3.0.0'

[tool.poetry.dependencies]
python = ">=3.13,<4"

[tool.poetry.group.test.dependencies]
pytest = "9.0.2"
pytest-cov = "7.0.0"
pytest-django = "4.11.1"
pytest-mock = "3.15.1"
tavern = "3.0.2"
fakeredis = "2.33.0"
pytest-env = "1.2.0"
responses = "0.25.8"
pytest-xdist = "3.8.0"
psutil = "7.1.3"
freezegun = "~=1.5.1"
pre-commit = "3.3.3"
s3transfer = "0.13.0"
mock = ">=5.1.0"
moto = ">=5.1.18"
requests-mock = "1.12.1"
factory-boy = "^3.3.3"

[tool.poetry.group.build.dependencies]
twine = ">=6.1.0"
packaging = ">=24.2"

[build-system]
requires = ['poetry-core (>=2.0.0,<3.0.0)']
build-backend = "poetry.core.masonry.api"
